### ISSUE TITLE
Base box download broken

### ISSUE THREAD

**Issue by superwilly** [weblogic-community/weblogic-vagrant#1]
The base box  as configured in Vagrantfile is not on dropbox anymore:

box:wls12c-centos-standalone willy$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos-6.4-x86_64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'centos-6.4-x86_64' (v0) for provider: virtualbox
    default: Downloading: https://dl.dropboxusercontent.com/s/yg9ceak6zd86wk7/centos-6.4-x86_64.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 401 Not Authorized

**Comment by biemond** [comment]
Thanks for reporting this

I updated this 6.4 box to centos 6.5, 6.6 & 7.0 

here you are already have the right vagrantfile values, I also added vmware

```
admin.vm.box = "centos-6.6-x86_64"
admin.vm.box_url = "https://dl.dropboxusercontent.com/s/ijt3ppej789liyp/centos-6.6-x86_64.box"

admin.vm.provider :vmware_fusion do |v, override|
  override.vm.box = "centos-6.6-x86_64-vmware"
  override.vm.box_url = "https://dl.dropboxusercontent.com/s/7ytmqgghoo1ymlp/centos-6.6-x86_64-vmware.box"
end

admin.vm.provider :vmware_fusion do |vb|
  vb.vmx["memsize"] = "3072"
end

admin.vm.provider :virtualbox do |vb|
  vb.customize ["modifyvm", :id, "--memory", "3072"]
  vb.customize ["modifyvm", :id, "--name"  , "admin"]
end
```

I will update this vagrant repo

**Comment by superwilly** [comment]
Thanks for quick response. I changed my Vagrantfile to use the new base box url and the download worked fine.

I am now getting this error:

```
box:wls12c-centos-standalone willy$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos-6.6-x86_64'...
==> default: Matching MAC address for NAT networking...
...
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
==> default: Info: Loading facts
==> default: Error: Duplicate declaration: Class[Orautils] is already declared; cannot redeclare at /tmp/vagrant-puppet-3/manifests/site.pp:226 on node vagrantcentos64.example.com
==> default: Error: Duplicate declaration: Class[Orautils] is already declared; cannot redeclare at /tmp/vagrant-puppet-3/manifests/site.pp:226 on node vagrantcentos64.example.com
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above
```

Is the Vagrantfile incomplete?

For example, the puppet modules are supposed to use a JDK and Weblogic supplied by the user, but there is now synced folder stuff in the Vagrantfile

**Comment by biemond** [comment]
Ok,

will also fix that

in the meantime you change this in the site.pp
https://github.com/weblogic-community/weblogic-vagrant/blob/master/wls12c-centos-standalone/puppet/manifests/site.pp

this should work :-)

```
 node 'vagrantcentos64' {
    include os2, wls12, wls12c_domain
    Class['os2']  -> Class['wls12'] -> Class['wls12c_domain'] -> Class['orautils']
 }
```

**Comment by biemond** [comment]
Done,

thanks
